INSERT INTO port_port (port, used, mach_id) VALUES (8082, 0, 1);
INSERT INTO port_port (port, used, mach_id) VALUES (8083, 0, 1);
INSERT INTO port_port (port, used, mach_id) VALUES (8084, 0, 1);
INSERT INTO port_port (port, used, mach_id) VALUES (8085, 0, 1);
INSERT INTO port_port (port, used, mach_id) VALUES (8086, 0, 1);
INSERT INTO port_port (port, used, mach_id) VALUES (8087, 0, 1);
INSERT INTO port_port (port, used, mach_id) VALUES (8088, 0, 1);
INSERT INTO port_port (port, used, mach_id) VALUES (8089, 0, 1);
INSERT INTO port_port (port, used, mach_id) VALUES (8090, 0, 1);
INSERT INTO port_port (port, used, mach_id) VALUES (8091, 0, 1);
SELECT * FROM port_port;